Add support for the FUSE_BATCH_FORGET operation
jacobsa/fuse pull request #123
Opened 2022-05-26 17:58 UTC by ironsmile

There are certain Kernel versions which do not send individual
Forget operations after they receive "not implemented" for Batch Forget.
One example is "5.4.0-110-generic" on Ubuntu 20.04. I am sure there are
plenty of others.

This leads to inode "leaks". Where reference counts are never decreased
and the inodes were left hanging around long after they are not needed
any more.

The best way to fix that was adding support for batch operations to the
lib. This way all users will be able to benefit from the batching
optimization.

2022-05-27 06:37 UTC, stapelberg requested changes
Thanks for your PR! Can you rebase it onto current master? I pushed a commit to fix CI on mac in the meantime.

2022-05-27 06:37 UTC, stapelberg commented on fuseops/ops.go
> +// Everything written in the ForgetInodeOp docs applies for the BatchForgetEnetry
typo: BatchForgetEntry

2022-05-27 06:43 UTC, ironsmile commented on fuseops/ops.go
> +// Everything written in the ForgetInodeOp docs applies for the BatchForgetEnetry
Well spotted! Fixed.

2022-05-27 06:44 UTC, ironsmile commented
You are welcome! I've rebased it to the latest master from 9 minutes ago too. Hope it builds now 😄

2022-05-27 06:49 UTC, merged

2022-05-27 06:49 UTC, stapelberg commented
Thanks!

2022-07-02 09:13 UTC, vitalif commented
Thanks, I did just the same thing yesterday and today I discovered that it's already done here :))

One thing I want to add is #126