ReadDir response cache POC
jacobsa/fuse pull request #162
Opened 2024-05-09 09:08 UTC by raj-prince

2024-05-14 14:33 UTC, stapelberg requested changes
Do you have an example for how to use this? Could any of the existing examples be adjusted to exercise this feature?

2024-05-14 14:33 UTC, stapelberg commented on fuseops/ops.go
> +	CacheDirContentAsPageCache bool
Please rename this field to `CacheDir` for consistency with the Linux kernel flag name (`FOPEN_CACHE_DIR`). That the page cache is used for caching is an implementation detail.

2024-05-14 14:33 UTC, stapelberg commented on fuseops/ops.go
> +	KeepDirContentPageCache bool
Please rename to `KeepCache` for consistency with the Linux kernel flag name (`FOPEN_KEEP_CACHE`). Also, the kernel documents this field as “don't invalidate the data cache on open”, so I think a better description is “KeepCache instructs the kernel to not invalidate the data cache on open calls”

2024-05-20 17:24 UTC, raj-prince commented
> Do you have an example for how to use this? Could any of the existing examples be adjusted to exercise this feature?

Added as part of `samples/caching_fs`.

2024-05-22 08:54 UTC, stapelberg approved these changes

2024-05-22 08:54 UTC, stapelberg commented on samples/cachingfs/caching_fs_test.go
> +	fmt.Print(t.Dir)
Remove debugging left-over

2024-05-22 08:54 UTC, stapelberg commented on fuseops/ops.go
> +	// CacheDir conveys the kernel to cache the response of next
conveys **to** the kernel

2024-05-22 08:54 UTC, stapelberg commented on samples/cachingfs/caching_fs.go
> +// SetCacheDir and  SetKeepDirCache can be used to control whether the response
nit: remove extra space

2024-05-22 09:07 UTC, stapelberg approved these changes

2024-05-22 09:08 UTC, merged